name: Deploy Ebook App Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 178.16.137.226
          username: rishabhvyas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          connect_timeout: 60s
          script: |
            # Navigate to the Frontend folder
            cd /home/rishabhvyas/EbookApp/Frontend
            
            # Update code
            git pull origin main
            
            # Initialize NVM for Node 24
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 24.2.0

            # Install and Build
            npm install
            npm run build
            
            # Restart only the frontend process
            pm2 restart next-frontend-ebook || pm2 start npm --name "next-frontend-ebook" -- start
            
            echo "âœ… Frontend Deployment Successful!"
